### ISSUE TITLE
not build on android studio this error 

### ISSUE THREAD

**Issue by CESARKHALID** [admin-ch/CovidCertificate-App-Android#188]
![no matching configuration](https://user-images.githubusercontent.com/73532128/124742511-b55c5800-df14-11eb-8e74-04a461cba944.png)

what i should do for i can resolve it

**Comment by goebelUB** [comment]
Did you run `git submodule update --init` [as per the README](https://github.com/admin-ch/CovidCertificate-App-Android#installation-and-building)?

**Comment by CESARKHALID** [comment]
please can guid me to add this git

**Comment by CESARKHALID** [comment]
please u can help me to build it 
i not reach to build it

**Comment by goebelUB** [comment]
Since you don't know what [git](https://en.wikipedia.org/wiki/Git) is, I assume you downloaded the Sources zip from the  assets in the [releases page](https://github.com/admin-ch/CovidCertificate-App-Android/releases)?
TIL that the `Sources` files that Github automatically generates for each release doesn't contain the submodules, and thus the `sdk` directory is empty.
I do recommend learning git though, it's an essential tool for software development. There's a lot of tutorials out there, do read around.

Anyway, v2.1.1 (not 2.1.0!) removed the dependency on the SDK as a submodule (and gets it from Maven instead). Using [that](https://github.com/admin-ch/CovidCertificate-App-Android/archive/refs/tags/v2.1.1-2110-wallet.zip) should work for you.
