### ISSUE TITLE
"cert light" & "export" inactive for French QRCode

### ISSUE THREAD

**Issue by divinerites** [admin-ch/CovidCertificate-App-Android#233]
Using 2.2.0 on android 10 (from Google Store)

All is fine except that the 2 options `certificat light` and `exporter` are inactive for my 2 French QRCode.

Is this expected for non-swiss certificate ?

**Comment by goebelUB** [comment]
Correct. Both features are only enabled for Swiss certificates (see 4232ed1c94445e141552b503c432804c3b99221b and https://github.com/admin-ch/CovidCertificate-App-Transformation-Service/commit/fbf3ac2754dbc2105d769278c46f946f68197c4f).

For the Certificate Light, see also [these news](https://www.watson.ch/fr/!187987343).
For the PDF export, note that the Swiss backend can only generate the Swiss design of the PDF. It makes sense to prevent people from disguising foreign certificates as Swiss ones. Furthermore, in Switzerland the [regulation](https://www.fedlex.admin.ch/eli/oc/2021/325/fr) sets out some rules of what needs to be in/on the certificate (see Art 12 and Appendix 1). It is reasonable to assume that other countries have similar regulations, so that's another hurdle.

**Comment by divinerites** [comment]
@goebelUB this make sense. Thanks for the quick response.
I'll close this issue then.
