### ISSUE TITLE
[Feature request] Notification for successful certificate transfers

### ISSUE THREAD

**Issue by inaert** [admin-ch/CovidCertificate-App-Android#263]
Dear team,

It would be great to get a notification when a transfer request has been fulfilled. Transfer requests are the recommended way in Zurich for receiving vaccination certificates issued for people vaccinated abroad, but the requests take an unpredictable amount of time to be processed, requiring frequent manual checks to see if the certificate has finally arrived. I assume a notification would also be useful for receiving test certificates.

**Comment by goebelUB** [comment]
This is already implemented. Because we don't use Google Play Services in this app, we cannot (easily + battery friendly) have push notifications on Android. Instead we have a worker that runs periodically.

So you will get a notification, but it may be slightly delayed.

We'll take your feedback into account, maybe we'll adjust the polling interval in the future.
