### ISSUE TITLE
Verifier app should show more details

### ISSUE THREAD

**Issue by RafaelBod** [admin-ch/CovidCertificate-App-Android#276]
For the time being, the verifier app only shows name and birthday after scanning a QR code.
Oddly, it does so independent if a light certificate or a normal certificate was scanned.
In my view, this behavior is desirable only for light certificates.
For normal certificates, it should display all information that are contained in the QR code (i.e. type of certificate, expiration date, etc.)
Otherwise it would be way to easy to for example forge a vaccinated certificate, by creating your own certificate with your desired expiration date and simply replacing the QR code with a currently valid test certificate.
Hope this makes sense, what I try to describe.

**Comment by goebelUB** [comment]
This is by design. Someone checking other people's certificate should only see the minimum set of information that is necessary for the combined ID check ("privacy by design").

Actually, if you look [at the code](https://github.com/admin-ch/CovidCertificate-SDK-Android/blob/main/sdk/src/main/java/ch/admin/bag/covidcertificate/sdk/android/models/VerifierCertificateHolder.kt), a verifier app that uses the SDK properly does not even have access to anything other than the name and date of birth. All other details are `internal` to the SDK.

Afaik the certificate light is a case of "doppelt hält besser" that was proposed by the [EDÖB](https://www.edoeb.admin.ch/edoeb/de/home.html) so that you as a user can "protect" yourself against discrimination by someone who is using a modified QR code scanner and is trying to find out whether you are vaccinated or "only" tested.

Yes, people can construct QR codes whose structure is valid and can be parsed. But the QR code contains a signature from an authority such as the BAG (or any ministry of health for international certs). Unless they manage to fake the signature as well, the verifier app won't accept the cert.

**Comment by RafaelBod** [comment]
Thanks for the answer and the explanation the code and the EDÖB. They do have a fair point.

Just as an explanation: The "exploit" I meant was not that someone would create his own QR code. But rather they would "cut and paste" a valid QR code from a test on a self-created (word-) document that corresponds to the same person and birthdate, but with a different certificate type (e.g. vaccination or recovery) and expiration date.
(The so-created document would also only work for the duration the test-QRcode is valid. However, there is no way to tell at the time of using the checker)
Hope this makes sense. Have a nice one.

**Comment by mkrummenacher** [comment]
I propose to re-open this issue. It's not necessary to show if someone is vaccinated or has recovered, but showing the expiration date would be helpful. There are situations, where it makes a difference if someone is tested or has a certificate with a longer validity.

Use cases I have encountered:
- Hotels
- Restaurants where you are regular guest
- Events like the Basler Herbstmesse, where you get a wristband for an entire week if the certificate is valid long enough

Currently, the expiration date is checked on the guest's phone, which is not secure.

It would also enhance usability for people like me who have their QR code printed onto a card.

My suggestion: The Verifier App should show the expiration date of the certificate. If someone doesn't like that, he can use the light certificate. One could discuss if the light certificate should be the default option, but I don't think it's necessary.
