### ISSUE TITLE
Self verification button used for verification

### ISSUE THREAD

**Issue by panmau** [admin-ch/CovidCertificate-App-Android#295]
This is a question that I'm not sure where else to put and didn't find much information about.

Recently more and more people are not using the scanner app but the self-verification button to control my certificate. This doesn't seem right to me though. I mean someone could use the code here, remove the verification and then has a 'valid' certificate.

Can you confirm whether this is how this button is intended to be used?

Maybe this option needs to be rethinked.

**Comment by FreddyKaiser** [comment]
Please address it quickly as more and more are using this to check the certificate validity instead of the verification app. 

I would vote for "2. Have the button simply not trigger the green checkmark animation" with:
* It should not give any feeling about "verification successfull"
* Drop the green color (QR Background, Message box)
* Change the message "The certificate is being verified" to "The certificate is being updated"
* Drop the explicit additional message "Verification successfull"

Just like it is displayed after the green stuff is disappearing. In case of "Update error", display the same messages / errors as when importing a PDF or scanning a new QR code

**Comment by simonerni** [comment]
Hi @goebelUB,

Any news on this? I'm sure also the folks coming from a privacy perspective (e.g. especially EDÖB) would appreciate a solution, since the current practice of using the button leads to a privacy issue as well - the verification service knows when I'm being checked for a certificate.

**Comment by denysvitali** [comment]
I would suggest removing the refresh button as a FAB but hiding it a little bit in the option, and yes, definitely dropping the green color and explaining what the button should be used for _every time that it's clicked_.  
  
Sadly nowadays people don't scan the QR code anymore, and those who should scan the QR code don't know what that button is, and why clicking it is not a replacement for scanning the certificate.  
  
The whole concept of the DGC is that the QR code presented to you cannot be trusted - and thus you need to scan it with an uncompromised device to prove its validity.  
  
That function on the app completely replace the "scan" behavior and thus everyone in Switzerland can recompile the app to show anything that will show the green color when that button is pressed.  
  
I switched to the light certificate, and I lost the count of people who still try to find the refresh button. When they don't find it, they simply don't scan the QR and they let me enter the venue / bar / restaurant.  
  
This sadly shows how such a bad UX jeopardizes the efforts of making a cryptographically secure solution like the DGC.

**Comment by vaubaehn** [comment]
We have similar experiences with official Corona-Warn-App in Germany, eventhough there is no green checkmark next to the QR code.
We have a check to validate EU business rules reachable in a submenu via a floating button next to QR code, that is "abused" by gate keepers instead of scanning the code.
However, I also strongly recommend the changes proposed in this issue.

I think, in the end it will rely on politics to integrate the check of QR codes into the COVID related legislation, and on massive promotion of the necessity to scan the code in the media. People who enter a venue where no reliable check is done should feel insecure about their own health.

Many greetings from the north.

**Comment by Tharadash** [comment]
I just had it happened to me yesterday - some restaurant staff "verified" my covid-cert by pressing on this button.
I'd suggest either altering the button behaviour as in #301 or "burying" it deep  in some menu at the bottom of the app when viewing a certificate.

**Comment by denysvitali** [comment]
Saw yesterday a queue of people at a restaurant showing their COVID Certificate and pressing on "verify" to show the checkmark.

I showed the cashier my Light Certificate. She tried to find the "Refresh" button to confirm tjat my certificate is valid, didn't found it, didn't scan it, said it was all good.

This needs to be fixed ASAP. I'll make a PR for the Android app soon.

**Comment by FreddyKaiser** [comment]
@denysvitali I created a PR #301 with updated checks where the green color is gone and the texts have been changed to "refreshing" instead of "validating". Feel free to review and update.

Personally I think it should go a step further and remove completely this button for the end users, therefore the PR has been updated with this. As many persons are now used to use this "refresh" button in the country, they will not see the difference and trust what the end user is showing to them; like they did for your "Light Certificate".

**Comment by denysvitali** [comment]
I'd personally keep the button as it is, and show a red warning on every click mentioning what the feature is used for.

A message in the four languages should show that clicking the button doesn't replace scanning, and it is actually meaningless for the person scanning the QR code.

**Comment by FreddyKaiser** [comment]
I didn't find any use case for this button, you? The refresh of the certificate is done transparently at the startup of the app. 
Going futher on your proposal, then the button should then be added to the "Light Certificate".Otherwise this will be the next "quick check" getting traction. People will see the time counter and think this is a valid certificate for this duration, no need to scan.

**Comment by ibauersachs** [comment]
It's now two months since I opened the iOS issue and we have to assume this is deliberately not dealt with. The only way to get anything moving would probably be to create an actual app that creates invalid QR-Codes for Mickey mouse etc. showing a green animated checkmark.

The refresh button needs to be gone. There's simply no valid usecase for it. And as @goebelUB mentioned, the app should show **only** the QR code, at the very least when it's zoomed. There's simply no information that should be shown, not the name, not the birthday, not the validity, the only thing necessary is the QR code.
In fact, the app itself is useless, the wallet app on iOS can do the same and I assume Android has something similar. Or any app that can show a QR code is sufficient. Even an image of the paper certificate is.

**Comment by denysvitali** [comment]
> I didn't find any use case for this button, you? The refresh of the certificate is done transparently at the startup of the app. 
> Going futher on your proposal, then the button should then be added to the "Light Certificate".Otherwise this will be the next "quick check" getting traction. People will see the time counter and think this is a valid certificate for this duration, no need to scan.

The only good reason for such a button is to mislead people.

I'd add a "Certificate valid only if scanned", right after the information that the certificate is valid only with a valid identity document, and the button notice explained above, together with another UI / UX for the validation process that should discourage the use of that button as an alternative to scanning.

**Comment by denysvitali** [comment]
Nobody ever showed how messed up (in terms of UX) this problem is. So here is a quick screen recording of the current behavior with a modified app (just to mock the verification part):

https://user-images.githubusercontent.com/4939519/142692818-317ec45b-8823-4879-a1a5-f02729577c9c.mp4


Now, I can tell you that due to this bad UI / UX, I can most probably take this modified app with me, visit any place in Switzerland and get in without any issue. The problem is that the people that are supposed to scan the QR code are clicking this button on the user phone (thus trusting the user) to check their certificate.  
  
Needless to say, this is not how the verification should happen. This positive action on the FAB click resulted in a switch in behavior of how the people that are supposed to scan the QR code approach the situation.  
On top of that, people anticipate the person scanning the QR by clicking the button themselves, and the verifier just trusts the person who pressed the button.  
  
I'll propose a couple of designs / implementations of how I would solve the issue, and make some PRs. This thing has to be fixed ASAP.

**Comment by ibauersachs** [comment]
Thanks for the recording! And yes, it happens exactly as you're describing (with very few notable exceptions).

Unfortunately, I think it's safe to assume that absolutely nothing is going to happen until after Nov. 28.

**Comment by denysvitali** [comment]
My initial proposal:

https://user-images.githubusercontent.com/4939519/142695929-c42fb04d-8071-47d2-b5fd-eb9e2083e8b0.mp4

**Comment by denysvitali** [comment]
And here is an improved version (better layout) related to the previous idea:

https://user-images.githubusercontent.com/4939519/142697923-aa333c96-3aa7-44ca-9a7a-e6ac0ca45771.mp4

**Comment by FreddyKaiser** [comment]
Maybe the Infos you display can be taken from the "Important" out of https://www.bag.admin.ch/bag/en/home/krankheiten/ausbrueche-epidemien-pandemien/aktuelle-ausbrueche-epidemien/novel-cov/covid-zertifikat/covid-zertifikat-pruefer-aussteller-technische-informationen.html#1851413288

At the end not sure that this will be enough. The "checkers" will go to Plan B and ask for the "Certificate Light" and look at the remaining time of validity. Most of the "checkers" don't have any Device to Scan actively and prefer to trust and use the one of the person to be verified.

Probably the FOPH and the press have to be taken in duty to inform the "checkers" properly on how to proceed.

**Comment by denysvitali** [comment]
This is with the fineprint added:
![Screenshot_20211119-233823.jpg](https://user-images.githubusercontent.com/4939519/142700254-538fd3c2-d318-4547-a1a3-68be92af4650.jpg)

**Comment by denysvitali** [comment]
Just to show how widespread the idea of "click the refresh button to validate" is. From today's news:

> GINEVRA - Un semplice click, lo schermo che diventa verde, ok si entra. Ma non tutte le strutture per il tempo libero applicano questo semplice controllo. In Svizzera romanda più di 15 attività sono state chiuse dalle autorità.

> GENEVA - A simple click, the screen turns green, and you're in. But not all leisure facilities apply this simple control. In French-speaking Switzerland, more than 15 businesses have been closed by the authorities.

Source: https://archive.md/0Pdvb

**Comment by panmau** [comment]
> This is with the fineprint added:

I personally don't think that this will help much as most users won't read the text.

Therefore I would lean more toward one of the other possible solutions that were initally outlined by @simonerni. I think that they will help to resolve the problem in a better way regarding minimizing the misuse of the button and UX:
> 1 Remove the button, refresh in the background
> 3 Hide the button in some other view

**Comment by denysvitali** [comment]
> I personally don't think that this will help much as most users won't read the text.

I don't care if the users won't read all the wall of text. The first part (the title) is what the person who verifies the certificate will read when the button is pressed - which is enough.  
  
If it happens consecutively on N people's phone, the person "scanning" the QR code by clicking on that button will realize the mistake and start scanning it correctly.  
  
My PR also includes a removal of the green validation bubble and relative text, avoiding any UI related visual saying that "certificate is good".  
  
Personally I think this is the best way to raise awareness on the issue, and the title + summary are enough to probably convince people that the button is not what they think it is.  
  
Hiding the button will only make things worse, as this will make other fake verification means (e.g: light QR certificate) take place: "counter on screen = certificate is good".  
  
I would suggest going with my proposal, and further hiding the light certificate countdown (or removing it entirely and implemeting #302.

**Comment by denysvitali** [comment]
Newest design proposal (shortened title, added an alert icon):
<p align="center">
<img src="https://user-images.githubusercontent.com/4939519/142723820-1c95b9c0-4ebb-44dc-a654-4963ac47de3e.png" width="300"/>
</p>

**Comment by timonburkard** [comment]
I had [reported](https://www.ncsc.admin.ch/ncsc/en/home/dokumentation/covid-certificate-pst/reporting_form.html) this problem to NCSC on October 15. Unfurtunately, I never heard back from them.

**Comment by FreddyKaiser** [comment]
Sorry but it's getting ridiculous, most if not all checks are done with this "Refresh" button on the to be controlled person's device.

Maybe activating the national boulevard press will get some traction in this small change. Creating a custom version where you can set any desired Name, Date of birth so that the validation will be nicely green on any custom name would be an attractive "demo". As fixed Certificate just take any valid one from the [CH Test Files](https://github.com/eu-digital-green-certificates/dgc-testdata/tree/main/CH)

**Comment by timonburkard** [comment]
@FreddyKaiser I agree! I have also played with this idea. However, I would not publish such a version due to abuse possibility. I guess a short demonstration video which shows the result would be sufficient to get the attention of e.g., [blick.ch](https://www.blick.ch).

Downside would be that this app and the government may lose trust by people who think it is a security/cryptographic issue, which is definitely not the case. But it might be difficult for the broad public to understand that it is just bad UI.

I would rather not risk that... Because, besides this issue, I think the COVID-Certificate has been implemented great. But, maybe we don't have a different choice than to activate the boulevard press. Except @goebelUB can assure as that this is a scheduled priority at [FOITT](https://www.bit.admin.ch/bit/en/home.html)?

**Comment by simonerni** [comment]
It has been almost 2 months now since this issue has been raised. Thus far, no-one has created such a fake app. If we’re being honest, for now it doesn't _really_ matter if the certificate is scanned or merely refreshed.

While it is not ideal, it still is a sufficient check!

Please @FreddyKaiser and everyone else: Do **not** create any such fake app - you're becoming exactly the adversary were trying to defend against here. 

Although you’d certainly create pressure, people will abuse the situation, people will get infected and suffer. And for what? Remember, the status quo is merely not ideal.

Second, engaging boulevard press will absolutely **tank** the public opinion of the certificate. You suddenly plant this bad idea into everybody’s mind - so someone with the technical abilities **will** follow up on it. You therefore **created** the very situation we all want to avoid. 

It’s been the same problem with impfausweis.ch – researchers ran to the media, instead of cooperating with the platform and coming up constructively with secure solutions. Now the public is stuck without a platform at all! There, the researchers also created the very problem they were warning the public from.

I’m still advocating for a middle ground solution, _nudging_ the users into doing validation correctly using the checking app, without unnecessary media fuss. To do this, I’d propose the following measures:

1. Educate the people scanning the certificates.
2. Make certificate scanning *easy*.
3. Educate the people showing the certificates.

Point 1 would best be done via industry representatives – e.g. restaurant “Verbände”, etc. issuing explicit guidelines.

Point 2 includes:
- Fast and reliable QR code scanning even for phones with non-ideal cameras
   - Maybe a paper is better? Why not offer a credit-card sized QR code if that helps?
   - Is there a better QR code scanning library? What about collaborations with commercial providers, e.g. Scandit?
- Can we come up with a secure way to link a profile picture to the certificate, thereby eliminating for most use cases a need to present an ID.

**Comment by FreddyKaiser** [comment]
Waiting for #336 to get approved and we can close this; thanks @denysvitali

**Comment by denysvitali** [comment]
Any update?

In the last 7 days I got checked at multiple locations in Zürich and Bern, and thankfully they consider my modified app and realized that they need to scan the QR code after they saw that pressing the button resulted in that error message of my PR.  
  
The biggest offender remains a famous Burger chain in Zürich HB: they completely ignored me when I told them that they _need_ to scan the certificate rather than just clicking the refresh button. They had nothing on their side to check the certificates. What a shame.

**Comment by kuon** [comment]
In the last days, my certificate was ONLY checked by asking me to press the self check button, about 20 times. Every time I explain how it works, but nobody actually listened to me. Today one person at a burger king lavaux near lausanne explicitly told me they were instructed to not scan them, which motivated me to open an issue, but I found this one. It comforts me that I am not the only one to think there is a problem.

I think the only proper solution to force scanning is to remove the name below the QR code.

I realize it might be cumbersome for people having multiple certificates, but if multiple certificates are installed, we could just show the first letter of the given name (and if two given name start with the same letter, display 2 and so on, unless two very similar names are added, it should be OK). We could also allow an alias creation in the form of emoji (to avoid the alias having a real name), when you add a certificate, you can select a series of emoji to represent it).

We could also have a "show name" button, but when pressed, it would display that huge warning "do not use it for check". Even if I still think hiding the name is the only solution to properly enforce correct checks.

Making a PWA that mimic the official app could be done in one afternoon, so I think (considering the current climate of anti vaccine) it won't be long until one appears. I also think we should not make one even for the "proof", we know it is possible, let's not make it easier.

**Comment by denysvitali** [comment]
Friendly ping @benz-ubique / @simonroesch 

Is there a reason why you are (deliberately?) ignoring the PR / issue?

**Comment by MrReSc** [comment]
I also think that a change needs to be made here soon. Otherwise, the fake app will show up soon. This will harm the whole system more than adapting this update function.

It will also cast a false light on open source in general as the press will not understand the issue.

**Comment by kuon** [comment]
The fake app will show up eventually, I don't think it will be widely used or be a big public health issue (which in the end is the whole point and only real concern).

But I am worried about a scenario where this goes public under a bad light and the developers and open source in general are pointed as being incompetent.

**Comment by vaubaehn** [comment]
> The fake app will show up eventually, I don't think it will be widely used or be a big public health issue (which in the end is the whole point and only real concern).

Some weeks ago, I would have had the same opinion.

Just speaking about experiences currently made in Germany:
We have a debate about the introduction of mandatory vaccinations and the application of 2G/3G rules. This led to an increasing division and radicalization between vaccination supporters and vaccination opponents. On the part of those who oppose vaccination, we see the use of forged vaccination passes more and more frequently. Since the introduction of the DCCs, the investigative proceedings against counterfeiters have added up to several thousand (sic!). Since anti-vaccination campaigners are well networked via Telegram or similar platforms, such a fake app would spread in no time at all. Not only in the times of Omicron, every single infection (which can then be traced back to forged certificates) contributes to an **exponential growth** in the infection rate. From this point of view, the use of a fake app is sure to have an impact on public health and can contribute to further divisions and radicalization. So I would be very careful with that.

Since we also have a similar button in our Corona warning app (albeit with a different function) and with similar effects, I support the concern and the PR here.

**Comment by FreddyKaiser** [comment]
Sorry guys but this clearly shows that this Refresh button is "works as designed" and they want the people to use this; otherwise they would have reacted quickly. With the latest version they even made it even worse with the info about 2G / 3G.

I bet there are already modified versions used in the field. It's just so easy to do.... and paper fakes are already out; just read the latest news of the boulevard press about St. Gallen. Especially that most of the control points are not using the Covid Check App anymore and rely fully on the enduser app or paper; WYSIWYG changed into WYSIWYT(rust)

Maybe a [responsible disclosure](https://en.wikipedia.org/wiki/Responsible_disclosure) would be adequate here before we jump to the press and make a great demonstration on how easy it is to get into any place.

**Comment by kuon** [comment]
Well, as a developer I have no data or evidence to say that this issue is exploited in a way that can actually have real public health impact as @vaubaehn suggested. Maybe some estimation could be done, but this is out of my field. As I said, I tend to trust people and thinking groups would organize to cheat and exploit this is nearly sci-fi to me.

Having said that, what I can assert is that the UX design is bad and encourage misuse, even with no malicious intent whatsoever. And that it would be very easy for a malicious actor to publish a web app (PWA) that prompt for any name and mimic the official app. It could even be bundled with a real shared certificate (that can easily be stolen with a picture of someones phone during a check and could be updated if invalidated), then it would show green on the "scanner", with the wrong name yes, but with a bit of social engineering, you could show your ID along YOUR phone with the fake name, and the person scanning would just remember "yeah it passed on my phone". Again, for me the only proper solution is to fully remove the name from the certificate.

**Comment by Mannshoch** [comment]
I personally would vote for removing the button.

After a release of an updated App, I would wait some Days until all apps Phones have updated.
After next selve check i would tell people that this possibility get removed by a certain date.
And after this day the button should disappear.

**Comment by denysvitali** [comment]
Okay, let's go down the responsible disclosure way.

Let's give Ubique / @admin-ch 30 days to comment on this issue / come up with an official statement.  
  
Failure to do so would result in a PoC shared with the public in form of an APK / website.  
  
I don't want to go down this way, but it's the only thing we can do to finally get them to solve this issue.  

I'll send this in CC to their info email address and to the government CSIRT.  
  
This isn't even responsible disclosure to be honest, the issue is already stated and a solution is already provided.  
  
If the situation doesn't change, on January 20, 2022 a PoC will be provided here and to the press. Sorry guys but apparently we have to go this way to solve the issue.

cc/ @goebelUB, @simonroesch, @benz-ubique, @UBaggeler, @maurhofer-ubique, @ubamrein

**Comment by denysvitali** [comment]
NCSC and Ubique have been informed by email about the responsible disclosure plan.

**Comment by panmau** [comment]
@denysvitali
Please **don't** create / provide such a POC to the press! Inflating this issue via the press won't help **at all**, as @simonerni explained above.
Below a short extract of the relevant comment:
> Second, engaging boulevard press will absolutely tank the public opinion of the certificate. You suddenly plant this bad idea into everybody’s mind - so someone with the technical abilities will follow up on it. You therefore created the very situation we all want to avoid.

**Comment by petarmarj** [comment]
In case you didn't get it: the repository is open. And the press is reading it anyway. Greetings: someone from the press.

**Comment by ibauersachs** [comment]
@petarmarj But you're the responsible press ;-)

Let's just close this issue. The no-reaction and addition of the "3G 2G" indication makes it quite clear that it works as intended. And given that it's apparently easily possible to get valid certificates as shown in https://www.watson.ch/!569351676 makes a fake app not even necessary.

**Comment by simonerni** [comment]
Publishing a PoC only serves selfish reasons. It will also lead to abuse, infections, hospital admissions, and ultimately deaths. I wouldn‘t want to be responsible for even a single one.

I‘m normally supportive of a responsible disclosure process. But this is already over, it’s an open repo, it‘s already publically disclosed (@petarmarj conveniently proves this). There is no „disclosure process“ anymore at this stage. We can just twiddle thumbs and write angry letters to the FOPH.

@denysvitali - in your certificate analysis repo you say: „Please - stay safe and get vaccinated!“
But now you go and hand out tools to not get vaccinated and make everyone around them unsafe. Isn‘t that a really hypocrit move?

**Comment by denysvitali** [comment]
> you go and hand out tools to not get vaccinated and make everyone around them unsafe. Isn‘t that a really hypocrit move?

Yes, it kind of is an hypocritical move, but I feel it's the only possible way to raise awareness on the issue.  
  
Doing it yourself is extremely simple, and only takes two steps:
1. Cloning the repo
1. Modifying the code to fulfill the green chdckmark requirement

It seems like @admin-ch and Ubique are both fine with this since they have been silent since a long time on the issue, and by now I'm pretty sure someone already created such an app and is using it.  
  
Maybe the responsible disclosure deadline will help move things, maybe not, we'll see.  
  
I don't intend to help any unvaccinated person to avoid the certificate checks - quite the opposite!  
  
I'll make sure my PoC will be clearly fake and will not be usable with any real name / surname.

**Comment by kuon** [comment]
The problem with making more "noise" around this issue is that I think it will clearly NOT be fixed, so any more publicity would give ideas to malicious actors.

**Comment by mofobo-bit** [comment]
Hi everyone, the project team would like to comment on this as follows:

First, we would like to thank you for your interest and ideas regarding this topic. We are aware of the issues you have raised in connection with the refresh button. Currently, possible solutions are under review. We will keep you updated within due notice.

**Comment by denysvitali** [comment]
> I think it will clearly NOT be fixed

If it's not going to be fixed, a PoC will hopefully make the people realize that a fix is indeed needed, and hopefully raise awareness.  
  
Don't get me wrong. I don't want help malicious actors use such a method, but by now we can assume someone in the wild already did that and he is using that.  
  
Responsible Disclosures are made exactly for this reason:
>  Hackers and computer security scientists have the opinion that it is their social responsibility to make the public aware of vulnerabilities with a high impact. Hiding these problems could cause a feeling of false security.

It's just sad to see that the efforts made to have a cryptographically secure COVID Certificate are jeopardized by a stupid UX mistake

**Comment by kuon** [comment]
> Hi everyone, the project team would like to comment on this as follows:
> 
> First, we would like to thank you for your interest and ideas regarding this topic. We are aware of the issues you have raised in connection with the refresh button. Currently, possible solutions are under review. We will keep you updated within due notice.

Well, I'm happy to have been wrong.

**Comment by simonerni** [comment]
@denysvitali No, it‘s not the only way to go about this issue - as outlined in my statement above. The way you‘re going about this feels a lot like blackmail to me.

I understand your idea, publishing exploits as PoC helps in many cases after a fix has been available for some time. But here, we‘re concerned with health. Harm is not unlikely, it‘s almost guaranteed to follow. I therefore urge you to tread with utmost caution in your actions.

And finally: 

Just because a person might‘ve done this already with some effort doesn‘t mean that suddendly everyone should be able to do this easily.

**Comment by kuon** [comment]
I agree with @simonerni . We are not speaking of breaking DRM or showing we can download a movie, I don't think putting anymore "pressure" would help. We got an official response, late yes, but we got it.

I don't think there is anything more to prove.

**Comment by denysvitali** [comment]
Without an official answer, the PoC would have only been the only way to move things.  
  
Thankfully we got a semi-official answer. I just wonder now how much it will take to solve the issue entirely.

**Comment by andyscanzio** [comment]
FYI, they started the dev over on the iOS side: https://github.com/admin-ch/CovidCertificate-App-iOS/tree/feature/reload-button-changes

**Comment by mofobo-bit** [comment]
Thanks again for everyone's input! We will be phasing the button out over the course of the next weeks.

**Comment by denysvitali** [comment]
Can you share a little bit what's the plan there?

From the iOS repo the approach seems similar to my proposal (alert on click + grace period): but I might be wrong

**Comment by denysvitali** [comment]
FYI:
 #373

**Comment by goebelUB** [comment]
> Can you share a little bit what's the plan there?

Sure, I can give some technical details:

The current plan is indeed to have a popup that is shown when the user clicks the FAB, just like you proposed.
The information popup will only be shown for a while (currently the idea is 2 weeks). After that, the FAB will be hidden completely.

In addition, we plan to not immediately show the info popup in the new version. Instead, we introduce a flag to configure it via the backend. This allows us to switch from "refresh" to "info" once the majority of users have upgraded.
The aim is to have a "cleaner cut" and to limit confusion among "checkers" when 50% of users are on the old version and still have the refresh button while the other 50% already have the info popup.

Finally, all of this will be accompanied by communication on other channels, e.g. [on the website](https://www.bag.admin.ch/bag/en/home/krankheiten/ausbrueche-epidemien-pandemien/aktuelle-ausbrueche-epidemien/novel-cov/covid-zertifikat/covid-zertifikat-pruefer-aussteller-technische-informationen.html#1851413288). This complements the information in the info popup, which is deliberately kept short and non-verbose.

**Comment by denysvitali** [comment]
Awesome! Thank you very much!

**Comment by denysvitali** [comment]
I honestly still don't think the press underatood the change.

> BERNA - Covid-pass alla mano. Ma per il via libera, bisogna attendere il semaforo verde. O almeno, fino a ieri, bisognava. Sì, perché da oggi per entrare al ristorante, al cinema o in palestra non sarà più necessario che l'addetto alla sicurezza o la cameriera tocchino lo schermo dei nostri telefoni e premano il pulsante di aggiornamento del nostro certificato Covid elettronico. Ora l'app fa tutto da sola, eseguendo il refresh in maniera automatica. 
> 
> Dando un'occhiata all'AppStore, la descrizione dell'ultimo aggiornamento dell'applicazione Covid Certificate indica infatti che a partire da oggi «la funzione di autoverifica (pulsante "aggiorna") sarà sostituita da una verifica automatica». E, se al momento del controllo qualcuno rimane interdetto, basta dare prova dell'eliminazione della funzionalità cliccando sul pulsante in basso a destra di informazione "i", che esplicita l'avvenuta modifica.
> 
> Secondo delle verifiche effettuate dal Blick, il nuovo aggiornamento è però già in funzione solo su Iphone, mentre su Android, al momento, appare ancora il pulsante di aggiornamento. 

https://archive.md/3yrkK

Which translates to:
> BERN - Covid-pass in hand. But for the green light, you have to wait for the green light. Or at least, until yesterday, you had to. Yes, because from now on, in order to enter a restaurant, a cinema or a gym, it will no longer be necessary for the security guard or the waitress to touch the screen of our phones and press the update button on our electronic Covid certificate. Now the app does it all by itself, performing the refresh automatically. 
> 
> Taking a look at the AppStore, the description of the latest update to the Covid Certificate app states that starting today "the self-check function (refresh button) will be replaced by an automatic check". And, if at the time of the check someone remains interdicted, it is sufficient to give proof of the elimination of the functionality by clicking on the button at the bottom right of information "i", which makes explicit the change.
> 
> According to Blick's tests, the new update is already working only on iPhone, while on Android, at the moment, the update button still appears.

I hope a press release from the government will follow, so that these media sources can stop disseminating false information.


Blick on the other hand reports the news in a better way, and only down below in the article explains the real reason for the change.  
  
The situation was so messed up that people thought that the removal of the refresh button and its suggestion to use the Covid Check app is actually a new way of verifying the certificates to avoid people touching your smartphone...

> Jetzt töplet im Restaurant niemand mehr Ihr Handy an
Neu wird das Zertifikat in der Corona-App automatisch geprüft. Fremde Töpel-Finger auf dem Handy-Display sind passé – und dem Missbrauch ein Riegel geschoben.

> Now no one taps your phone in the restaurant
> The certificate is now automatically checked in the Corona app.  Strange dope fingers on the cell phone display are a thing of the past - and a stop has been put to abuse.

https://archive.md/AsDlR

---

It's still somehow a success, but I still think this has to be addressed with a press release, either from the government, or at this point the change is public by some more trchnically skilled journalists (looking at you @petarmarj)

**Comment by panmau** [comment]
As the self-verification button is now not available anymore, I think that we can close this issue.
Thanks again for implementing this change!
