### ISSUE TITLE
Disallow Screenshots & more

### ISSUE THREAD

**Issue by informatik-bks** [admin-ch/CovidCertificate-App-Android#55]
- Disallow Screenshots for the app
- Use a counter or something other to make sure nobody just can make a picture of the displayed data

**Comment by simonerni** [comment]
@sschueller If I understood the approach correctly, the certificate is valid as long as it is not included in a certificate revocation list.

The displayed data (the certificate, encoded as QR code), does thus not change and stays valid. It is easily copiable by anyone. This should not be an issue, as the certificate is bound to the name of the certificate holder. During verification with the verifier app, presumably the verifier will check out-of-bands the identity of the person showing the certificate, e.g. with his/her passport.

The benefits of such an approach is that it also allows printouts of the QR code (hence the PDF generation), which is useful during traveling as an additional safeguard in case of device loss or empty battery. It also allows the population with no smartphone to present a Covid certificate.

Please correct me if I‘m misunderstanding something here.

@informatik-bks Disallowing screenshots may easily be bypassed. Any counter on the GUI etc may be faked trivially as well. Would you care to elaborate what scenario you want to prevent with your proposed measures?

**Comment by informatik-bks** [comment]
it was just an idea to make the it more secure

**Comment by dominikponniah** [comment]
@simonerni I personally do like @informatik-bks idea! 

As i developed once a Contact-Tracing-App for Restaurants i faced the big problem: Humans! 
You are right, that bypassing is very easy, but how do you guarantee, that the person checking the Code does also check if it is a screenshot? People looking the same or members of the Family which do have similar or same names can trick the system very well in this case.

The realization would be " or maybe" easy:

- Add a Timestamp as Parameter to the QR-Code which gets validated with the Verificator. Just like at the SBB-App the QR-Code would never be the same.

- Also a Animation in the center of the Code (like as some QR-Codes uses Icons) would be a good verifier just by looking at it.

**Comment by simonerni** [comment]
@dominikponniah 

1) The amount of signatures the HSM would need to perform would be drastically increased, this would limit scalability a bit and increase operational costs a lot.
2) The certificate also exists in a paper form, essentially a durable screenshot. This is the main reason why I don‘t think this prevention is possible or would make sense in the first place.

BTW: I‘m not affiliated to the developers in any way, feel free to keep the discussion open :-)

**Comment by dominikponniah** [comment]
@simonerni

Yes you are right, sometimes I forgot that we have approx 6 Million Users of such apps in Switzerland 😅.

But if we talk technically, wouldn't that code be parsed or generated locally? The Data which is issued by the BIT/BAG would be the same, there would just be an additional value in this (e. G. JSON Object)...

But you are right that's not a big deal because there are also people with paper-codes.

**Rather an off-topic:**
Are there any informations about the format of these physical-codes? The idea of people walking around with big A4-Sheets scares me and I think wouldn't be very suitable if these codes could also be used at Festivals or in a public swim-area.

I like an idea of a small card (like these you get from REGA) every year. Therefore everybody can store it for example in the purse or at the back of a non-supported smartphone. 

As I read the minimal version for Android is 7.0... There are still (especially elderly-devices) which are running 5.0 or 6.0.

To cover costs of a card like this maybe a price of 1 to 2 Francs would be suitable for everyone I guess.

**Comment by goebelUB** [comment]
One thing to keep in mind is that the format of the data contained in the QR code should be compatible with the EU's Digital COVID Certificate. You can find more details on their spec [here](https://github.com/ehn-digital-green-development/hcert-spec) and [here](https://github.com/ehn-digital-green-development/ehn-dgc-schema).

**Comment by MarcelWaldvogel** [comment]
Apparently, v2.0.0 does include this (mis-)feature that I found out about when trying to document a potential problem. Screenshots are just too handy and I do not really see any risk that depends on the screenshot.
