### ISSUE TITLE
Verifier: Possible DoS (ZIP Bomb) while de-compressing untrusted QR Code

### ISSUE THREAD

**Issue by simonerni** [admin-ch/CovidCertificate-App-Android#56]
In the Verifier App, the verify chain includes this decompressor, seemingly without a size limit for the decompressed byte array.

https://github.com/admin-ch/CovidCertificate-App-Android/blob/060a40c7510c113a304ebe515e0f7833ae03623b/eval/src/main/java/ch/admin/bag/covidcertificate/eval/chain/DecompressionService.kt#L15

By including a specially crafted byte array as QR Code that decompresses to a very large byte array, could this lead to a DoS attack (i.e. a crash of the app after running out of memory)?

**Comment by goebelUB** [comment]
Thanks for pointing out this issue.

For the apps right now the impact is limited.

This is because all input fed to this function comes from a QR code. QR codes can contain only [<4500 characters](https://www.qrcode.com/en/about/version.html). Considering a worst-case compression factor of [roughly 1000:1](http://www.zlib.net/zlib_tech.html) we should end up with no more than 5MB.

A fix is pending in #60 .

**Comment by simonerni** [comment]
Indeed you are right, I was having this paper in mind when drafting up the issue;

https://www.usenix.org/system/files/woot19-paper_fifield_0.pdf

But upon more careful inspection it‘s adamant that it is not working for streaming parsers like the ones used here. But even if any other approach should crop up, I think this issue is handled nicely now.

I thank you for the rapid fix.
