### ISSUE TITLE
App dependencies, minimal Android version and requirements

### ISSUE THREAD

**Issue by ericbl** [admin-ch/CovidCertificate-App-Android#58]
Please add in the Readme or App document a chapter about android requirements:
a) HW requirements if any
b) minimum Android version where the app can run - testing on old smartphone like on Android 4.4 could be helpful here
c) any external SW dependencies.

**Comment by steveacab** [comment]
Min Android version is 6.0 according by SDK 23 min required.

**Comment by goebelUB** [comment]
Correct, it was originally Android 7 / API 24, we've since lowered it to Android 6 / API 23.

The minimum Android version is now documented in the readme. I won't document the other dependencies, as they are either obvious (your phone needs a camera to scan QR codes) or redundant (documented in the `build.gradle` for devs and in-app imprint for users, so maintaining a third place would be unecessary extra effort).
