### ISSUE TITLE
Building APKs

### ISSUE THREAD

**Issue by dominikponniah** [admin-ch/CovidCertificate-App-Android#67]
Is there any possibility to build the APKs? I do always get strange error messages:

`Could not determine the dependencies of task ':wallet:compileAbnDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':wallet:abnDebugCompileClasspath'.
   > Could not resolve project :sdk.
     Required by:
         project :wallet > project :common
      > No matching configuration of project :sdk was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'version' with value 'abn', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - None of the consumable configurations have attributes.`

Keystore and everything is set up properly!

**Comment by goebelUB** [comment]
Did you run `git submodule update --init` after checking out the project? The SDK is currently added as a submodule, which may not be properly fetched when doing a simple `git clone`.

**Comment by dominikponniah** [comment]
Yes I did and also tried again... 

But i am getting always this strange Error:

```
Cloning into 'C:/Users/Dominik/Desktop/CovidCertificate-App-Android/sdk'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:admin-ch/CovidCertificate-SDK-Android.git' into submodule path 'C:/Users/Dominik/Desktop/CovidCertificate-App-Android/sdk' failed
Failed to clone 'sdk'. Retry scheduled
Cloning into 'C:/Users/Dominik/Desktop/CovidCertificate-App-Android/sdk'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:admin-ch/CovidCertificate-SDK-Android.git' into submodule path 'C:/Users/Dominik/Desktop/CovidCertificate-App-Android/sdk' failed
Failed to clone 'sdk' a second time, aborting
```

But when checking the Repository using Browser, it is visible and i read the code in it...

**Comment by goebelUB** [comment]
The submodule is added as via ssh, not https.

I [see](https://github.com/dominikponniah.keys) that you haven't added any to your account. Could you [add one to your account](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh) and then try again?

**Comment by dominikponniah** [comment]
Okay, that worked! Thanks for this.

But the Build-Problem still exists, when I run the Commands Provided:
```
$ ./gradlew verifier:assembleProdRelease
$ ./gradlew wallet:assembleProdRelease
```

**Comment by goebelUB** [comment]
If you are getting the an error along these lines:
```sh
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':verifier:packageProdRelease'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > SigningConfig "release" is missing required property "storePassword".
```
then the issue is that you haven't created a keystore, or Gradle doesn't find all the properties it needs.

Gradle will try to read the [keystore-related fields](https://github.com/admin-ch/CovidCertificate-App-Android/blob/main/verifier/build.gradle#L67) either from your global `~/.gradle/gradle.properties` or from the [`local.properties`](https://github.com/admin-ch/CovidCertificate-App-Android/blob/main/verifier/build.gradle#L24) at the root of the repo.
You can configure the keystore file location + password and key alias + password in either of those fields, or pass them as command line arguments to Gradle.

-----

If you don't want to fight with signing right now, you can build the debug version by replacing `Release` with `Debug`:
```sh
$ ./gradlew verifier:assembleProdDebug
```
Note that a) the output path will differ accordingly, and b) you should only to this for testing and use a properly signed build for production.

**Comment by dominikponniah** [comment]
Thanks @goebelUB !
I tried it firstly using the Debug-Build-Process. Then i opened the full project inside Android-Studio and i was able to build the Apps using a Keystore.
