### ISSUE TITLE
[Feature] Import from PDF directly

### ISSUE THREAD

**Issue by sbor23** [admin-ch/CovidCertificate-App-Android#90]
### Current behavior

To add a certificate, the user needs the QR code on paper or as a PDF on a second device in order to scan it.

### Expected behavior

Next to the "ADD" functionality with the barcode scanner via camera, it would be useful if an option to "ADD FROM PDF" would exist.
This would solve the issue in case no paper or second device is available at the time.

**Comment by goebelUB** [comment]
The upcoming release supports acting as a share target for PDFs. You will be able to share the PDF from any other app and select the COVID Certificate app to import your certificate.

The "opposite" direction (having an Import-from-PDF button in the app) is under review.

**Comment by robertbastian** [comment]
Being a share target for PDF is not great, as the app is not a PDF viewer. If the user has no other PDF viewers installed, the system will now ask for every PDF whether to open in the built-in viewer or in the wallet, whereas before the PDF would just open.

**Comment by bakito** [comment]
I'd also prefer an 'add from pdf' button  to a share target.

**Comment by goebelUB** [comment]
> the app is not a PDF viewer

What you describe means registering for intents with [ACTION_VIEW](https://developer.android.com/reference/android/content/Intent#ACTION_VIEW). This is different from [ACTION_SEND](https://developer.android.com/reference/android/content/Intent#ACTION_SEND), which is what we [implement](https://github.com/admin-ch/CovidCertificate-App-Android/blob/v1.2.0-1200-wallet/wallet/src/main/AndroidManifest.xml#L35).
When I said "share target" I was referring to COVID cert being included in the list of apps that come up in what Android calls the ["share sheet"](https://developer.android.com/images/training/sharing/sharesheet_api29.png) (which in turn shows when you click "Share" in any reasonable app).

So the flow is: download PDF -> open in your favourite viewer -> click share -> select COVID cert -> done.
Maybe this flow is more natural on iOS, since the landscape of (preinstalled) PDF viewers varies greatly on Android?

> I'd also prefer an 'add from pdf' button to a share target.

Luckily the two are not mutually exclusive. :) It's a personal preference. Arguably the share flow is faster when you are viewing the PDF anyway.
Additionally, the share target was a quick way to bridge the gap while the button UI and UX were under review (remember that there are 3 organisations involved as stakeholders!). You can't just slap an extra button on the main screen, it needs to properly fit in.

But rejoice, the upcoming v2.0 has a big button on the Android app's main screen as another way to do the PDF import.

**Comment by goebelUB** [comment]
v2.0.0 is now being rolled out and includes a PDF-import-button in the app.
